// <auto-generated />
using System;
using GestionResiduos.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionResiduos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260326015940_SistemaCompleto")]
    partial class SistemaCompleto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("GestionResiduos.Models.Residuo", b =>
                {
                    b.Property<int>("IdResiduo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaRecoleccionResiduo")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameResiduo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PesoResiduo")
                        .HasColumnType("REAL");

                    b.Property<string>("TipoResiduo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdResiduo");

                    b.ToTable("Residuos");

                    b.HasData(
                        new
                        {
                            IdResiduo = 1,
                            FechaRecoleccionResiduo = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameResiduo = "Cascara de Guineo",
                            PesoResiduo = 0.5,
                            TipoResiduo = "Organico"
                        },
                        new
                        {
                            IdResiduo = 2,
                            FechaRecoleccionResiduo = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameResiduo = "Botella de Vidrio rota",
                            PesoResiduo = 1.0,
                            TipoResiduo = "Vidrio"
                        },
                        new
                        {
                            IdResiduo = 3,
                            FechaRecoleccionResiduo = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameResiduo = "Botellas de Agua",
                            PesoResiduo = 1.5,
                            TipoResiduo = "Plastico"
                        },
                        new
                        {
                            IdResiduo = 4,
                            FechaRecoleccionResiduo = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameResiduo = "Restos de comida",
                            PesoResiduo = 2.0,
                            TipoResiduo = "Organico"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
