// <auto-generated />
using System;
using GestionResiduos.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionResiduos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("GestionResiduos.Models.Residuo", b =>
                {
                    b.Property<int>("IdResiduo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaRecoleccionResiduo")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameResiduo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PespResiduo")
                        .HasColumnType("REAL");

                    b.Property<string>("TipoResiduo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdResiduo");

                    b.ToTable("Residuos");
                });
#pragma warning restore 612, 618
        }
    }
}
